os: windows
before_script:
  - yarn install
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER markky WITH PASSWORD '92Axq@qwZU$werqklcme212';" -U postgres
  - yarn run initdb
language: node_js
node_js:
  - 'stable'
  - '12.14.0'
cache:
  directories:
    - 'node_modules'

services:
  - postgresql

addons:
  postgresql: '11'
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
env:
  global:
    - PGPORT=5433
    - PGUSER=postgres
    - PGHOST=localhost
