before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - yarn run initdb
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"

services:
  - postgresql

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5433